"""Country ISO code and continent/region inference.

Pure functions, no network. Designed for the enrichment step in the
job-collection pipeline: collectors that receive structured country
data from the ATS API set ``country_iso`` directly; the remaining jobs
get a best-effort inference from their free-text ``location`` field.

``region`` (continent) is always derived from ``country_iso`` via a
static lookup table when the country is known.
"""

from __future__ import annotations

import re as _re

# ---------------------------------------------------------------------------
# Country name → ISO 3166-1 alpha-2
# ---------------------------------------------------------------------------
# English names, common variants, and demonyms.  Every key is lowercase.
# When two countries share a demonym (e.g. "georgian" -> GE or DMZ?),
# the more-likely target for job listings wins.

_COUNTRY_NAME_TO_ISO: dict[str, str] = {
    "afghanistan": "AF",
    "aland islands": "AX",
    "albania": "AL",
    "algeria": "DZ",
    "american samoa": "AS",
    "andorra": "AD",
    "angola": "AO",
    "anguilla": "AI",
    "antarctica": "AQ",
    "antigua and barbuda": "AG",
    "argentina": "AR",
    "armenia": "AM",
    "aruba": "AW",
    "australia": "AU",
    "austria": "AT",
    "azerbaijan": "AZ",
    "bahamas": "BS",
    "bahrain": "BH",
    "bangladesh": "BD",
    "barbados": "BB",
    "belarus": "BY",
    "belgium": "BE",
    "belize": "BZ",
    "benin": "BJ",
    "bermuda": "BM",
    "bhutan": "BT",
    "bolivia": "BO",
    "bonaire": "BQ",
    "bosnia and herzegovina": "BA",
    "bosnia": "BA",
    "botswana": "BW",
    "bouvet island": "BV",
    "brazil": "BR",
    "british indian ocean territory": "IO",
    "brunei darussalam": "BN",
    "brunei": "BN",
    "bulgaria": "BG",
    "burkina faso": "BF",
    "burundi": "BI",
    "cabo verde": "CV",
    "cape verde": "CV",
    "cambodia": "KH",
    "cameroon": "CM",
    "canada": "CA",
    "cayman islands": "KY",
    "central african republic": "CF",
    "chad": "TD",
    "chile": "CL",
    "china": "CN",
    "christmas island": "CX",
    "cocos islands": "CC",
    "colombia": "CO",
    "comoros": "KM",
    "congo": "CG",
    "congo democratic republic": "CD",
    "cook islands": "CK",
    "costa rica": "CR",
    "côte d'ivoire": "CI",
    "cote d'ivoire": "CI",
    "ivory coast": "CI",
    "croatia": "HR",
    "cuba": "CU",
    "curaçao": "CW",
    "cyprus": "CY",
    "czech republic": "CZ",
    "czechia": "CZ",
    "denmark": "DK",
    "djibouti": "DJ",
    "dominica": "DM",
    "dominican republic": "DO",
    "ecuador": "EC",
    "egypt": "EG",
    "el salvador": "SV",
    "equatorial guinea": "GQ",
    "eritrea": "ER",
    "estonia": "EE",
    "eswatini": "SZ",
    "swaziland": "SZ",
    "ethiopia": "ET",
    "falkland islands": "FK",
    "faroe islands": "FO",
    "fiji": "FJ",
    "finland": "FI",
    "france": "FR",
    "french guiana": "GF",
    "french polynesia": "PF",
    "french southern territories": "TF",
    "gabon": "GA",
    "gambia": "GM",
    "georgia": "GE",
    "germany": "DE",
    "deutschland": "DE",
    "ghana": "GH",
    "gibraltar": "GI",
    "great britain": "GB",
    "greece": "GR",
    "greenland": "GL",
    "grenada": "GD",
    "guadeloupe": "GP",
    "guam": "GU",
    "guatemala": "GT",
    "guernsey": "GG",
    "guinea": "GN",
    "guinea-bissau": "GW",
    "guyana": "GY",
    "haiti": "HT",
    "heard island and mcdonald islands": "HM",
    "holy see": "VA",
    "vatican city": "VA",
    "honduras": "HN",
    "hong kong": "HK",
    "hungary": "HU",
    "iceland": "IS",
    "india": "IN",
    "indonesia": "ID",
    "iran": "IR",
    "iraq": "IQ",
    "ireland": "IE",
    "isle of man": "IM",
    "israel": "IL",
    "italy": "IT",
    "jamaica": "JM",
    "japan": "JP",
    "jersey": "JE",
    "jordan": "JO",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "kiribati": "KI",
    "korea": "KR",
    "south korea": "KR",
    "north korea": "KP",
    "kosovo": "XK",
    "kuwait": "KW",
    "kyrgyzstan": "KG",
    "laos": "LA",
    "latvia": "LV",
    "lebanon": "LB",
    "lesotho": "LS",
    "liberia": "LR",
    "libya": "LY",
    "liechtenstein": "LI",
    "lithuania": "LT",
    "luxembourg": "LU",
    "macau": "MO",
    "madagascar": "MG",
    "malawi": "MW",
    "malaysia": "MY",
    "maldives": "MV",
    "mali": "ML",
    "malta": "MT",
    "marshall islands": "MH",
    "martinique": "MQ",
    "mauritania": "MR",
    "mauritius": "MU",
    "mayotte": "YT",
    "mexico": "MX",
    "micronesia": "FM",
    "moldova": "MD",
    "monaco": "MC",
    "mongolia": "MN",
    "montenegro": "ME",
    "montserrat": "MS",
    "morocco": "MA",
    "mozambique": "MZ",
    "myanmar": "MM",
    "namibia": "NA",
    "nauru": "NR",
    "nepal": "NP",
    "netherlands": "NL",
    "new caledonia": "NC",
    "new zealand": "NZ",
    "nicaragua": "NI",
    "niger": "NE",
    "nigeria": "NG",
    "niue": "NU",
    "norfolk island": "NF",
    "north macedonia": "MK",
    "northern mariana islands": "MP",
    "norway": "NO",
    "oman": "OM",
    "pakistan": "PK",
    "palau": "PW",
    "palestine": "PS",
    "panama": "PA",
    "papua new guinea": "PG",
    "paraguay": "PY",
    "peru": "PE",
    "philippines": "PH",
    "pitcairn": "PN",
    "poland": "PL",
    "portugal": "PT",
    "puerto rico": "PR",
    "qatar": "QA",
    "réunion": "RE",
    "romania": "RO",
    "russia": "RU",
    "rwanda": "RW",
    "saint barthélemy": "BL",
    "saint helena": "SH",
    "saint kitts and nevis": "KN",
    "saint lucia": "LC",
    "saint martin": "MF",
    "saint pierre and miquelon": "PM",
    "saint vincent and the grenadines": "VC",
    "samoa": "WS",
    "san marino": "SM",
    "sao tome and principe": "ST",
    "saudi arabia": "SA",
    "senegal": "SN",
    "serbia": "RS",
    "seychelles": "SC",
    "sierra leone": "SL",
    "singapore": "SG",
    "sint maarten": "SX",
    "slovakia": "SK",
    "slovenia": "SI",
    "solomon islands": "SB",
    "somalia": "SO",
    "south africa": "ZA",
    "south georgia and the south sandwich islands": "GS",
    "south sudan": "SS",
    "spain": "ES",
    "sri lanka": "LK",
    "sudan": "SD",
    "suriname": "SR",
    "svalbard and jan mayen": "SJ",
    "sweden": "SE",
    "switzerland": "CH",
    "syria": "SY",
    "taiwan": "TW",
    "tajikistan": "TJ",
    "tanzania": "TZ",
    "thailand": "TH",
    "timor-leste": "TL",
    "togo": "TG",
    "tokelau": "TK",
    "tonga": "TO",
    "trinidad and tobago": "TT",
    "tunisia": "TN",
    "turkey": "TR",
    "turkmenistan": "TM",
    "turks and caicos islands": "TC",
    "tuvalu": "TV",
    "uganda": "UG",
    "ukraine": "UA",
    "united arab emirates": "AE",
    "united kingdom": "GB",
    "uk": "GB",
    "united states": "US",
    "united states of america": "US",
    "uruguay": "UY",
    "uzbekistan": "UZ",
    "vanuatu": "VU",
    "venezuela": "VE",
    "viet nam": "VN",
    "vietnam": "VN",
    "virgin islands british": "VG",
    "virgin islands us": "VI",
    "wallis and futuna": "WF",
    "western sahara": "EH",
    "yemen": "YE",
    "zambia": "ZM",
    "zimbabwe": "ZW",
}

# ---------------------------------------------------------------------------
# US state names -> "US"
# ---------------------------------------------------------------------------
_US_STATES: dict[str, str] = {
    "alabama": "US",
    "alaska": "US",
    "arizona": "US",
    "arkansas": "US",
    "california": "US",
    "colorado": "US",
    "connecticut": "US",
    "delaware": "US",
    "florida": "US",
    "georgia": "US",
    "hawaii": "US",
    "idaho": "US",
    "illinois": "US",
    "indiana": "US",
    "iowa": "US",
    "kansas": "US",
    "kentucky": "US",
    "louisiana": "US",
    "maine": "US",
    "maryland": "US",
    "massachusetts": "US",
    "michigan": "US",
    "minnesota": "US",
    "mississippi": "US",
    "missouri": "US",
    "montana": "US",
    "nebraska": "US",
    "nevada": "US",
    "new hampshire": "US",
    "new jersey": "US",
    "new mexico": "US",
    "new york": "US",
    "north carolina": "US",
    "north dakota": "US",
    "ohio": "US",
    "oklahoma": "US",
    "oregon": "US",
    "pennsylvania": "US",
    "rhode island": "US",
    "south carolina": "US",
    "south dakota": "US",
    "tennessee": "US",
    "texas": "US",
    "utah": "US",
    "vermont": "US",
    "virginia": "US",
    "washington": "US",
    "west virginia": "US",
    "wisconsin": "US",
    "wyoming": "US",
    "district of columbia": "US",
    "washington dc": "US",
}

# ---------------------------------------------------------------------------
# Canadian province/territory names -> "CA"
# ---------------------------------------------------------------------------
_CA_PROVINCES: dict[str, str] = {
    "alberta": "CA",
    "british columbia": "CA",
    "manitoba": "CA",
    "new brunswick": "CA",
    "newfoundland and labrador": "CA",
    "newfoundland": "CA",
    "northwest territories": "CA",
    "nova scotia": "CA",
    "nunavut": "CA",
    "ontario": "CA",
    "prince edward island": "CA",
    "quebec": "CA",
    "saskatchewan": "CA",
    "yukon": "CA",
}

# ---------------------------------------------------------------------------
# Combine all region-based lookups into one table for scanning.
# Longer keys first so "new york" matches before "york" fictionally
# would — though in practice none of our tables overlap problematically.
# ---------------------------------------------------------------------------
_LOCATION_ISO_LOOKUP: dict[str, str] = {}
for _d in (_COUNTRY_NAME_TO_ISO, _US_STATES, _CA_PROVINCES):
    for k, v in _d.items():
        if k not in _LOCATION_ISO_LOOKUP:
            _LOCATION_ISO_LOOKUP[k] = v

# ---------------------------------------------------------------------------
# ISO 3166-1 alpha-2 -> Continent
# ---------------------------------------------------------------------------

_COUNTRY_TO_REGION: dict[str, str] = {
    "DZ": "Africa",
    "IO": "Africa",
    "AO": "Africa",
    "SH": "Africa",
    "YT": "Africa",
    "RE": "Africa",
    "TF": "Africa",
    "BJ": "Africa",
    "BW": "Africa",
    "BF": "Africa",
    "BI": "Africa",
    "CV": "Africa",
    "CM": "Africa",
    "CF": "Africa",
    "TD": "Africa",
    "KM": "Africa",
    "CG": "Africa",
    "CD": "Africa",
    "CI": "Africa",
    "DJ": "Africa",
    "EG": "Africa",
    "GQ": "Africa",
    "ER": "Africa",
    "SZ": "Africa",
    "ET": "Africa",
    "GA": "Africa",
    "GM": "Africa",
    "GH": "Africa",
    "GN": "Africa",
    "GW": "Africa",
    "KE": "Africa",
    "LS": "Africa",
    "LR": "Africa",
    "LY": "Africa",
    "MG": "Africa",
    "MW": "Africa",
    "ML": "Africa",
    "MR": "Africa",
    "MU": "Africa",
    "MA": "Africa",
    "MZ": "Africa",
    "NA": "Africa",
    "NE": "Africa",
    "NG": "Africa",
    "RW": "Africa",
    "ST": "Africa",
    "SN": "Africa",
    "SC": "Africa",
    "SL": "Africa",
    "SO": "Africa",
    "ZA": "Africa",
    "SS": "Africa",
    "SD": "Africa",
    "TZ": "Africa",
    "TG": "Africa",
    "TN": "Africa",
    "UG": "Africa",
    "EH": "Africa",
    "ZM": "Africa",
    "ZW": "Africa",
    "AQ": "Antarctica",
    "AF": "Asia",
    "AM": "Asia",
    "AZ": "Asia",
    "BH": "Asia",
    "BD": "Asia",
    "BT": "Asia",
    "BN": "Asia",
    "KH": "Asia",
    "CN": "Asia",
    "CY": "Asia",
    "GE": "Asia",
    "HK": "Asia",
    "IN": "Asia",
    "ID": "Asia",
    "IR": "Asia",
    "IQ": "Asia",
    "IL": "Asia",
    "JP": "Asia",
    "JO": "Asia",
    "KZ": "Asia",
    "KW": "Asia",
    "KG": "Asia",
    "LA": "Asia",
    "LB": "Asia",
    "MO": "Asia",
    "MY": "Asia",
    "MV": "Asia",
    "MN": "Asia",
    "MM": "Asia",
    "NP": "Asia",
    "KP": "Asia",
    "OM": "Asia",
    "PK": "Asia",
    "PS": "Asia",
    "PH": "Asia",
    "QA": "Asia",
    "SA": "Asia",
    "SG": "Asia",
    "KR": "Asia",
    "LK": "Asia",
    "SY": "Asia",
    "TW": "Asia",
    "TJ": "Asia",
    "TH": "Asia",
    "TL": "Asia",
    "TR": "Asia",
    "TM": "Asia",
    "AE": "Asia",
    "UZ": "Asia",
    "VN": "Asia",
    "YE": "Asia",
    "AL": "Europe",
    "AD": "Europe",
    "AT": "Europe",
    "BY": "Europe",
    "BE": "Europe",
    "BA": "Europe",
    "BG": "Europe",
    "HR": "Europe",
    "CZ": "Europe",
    "DK": "Europe",
    "EE": "Europe",
    "FO": "Europe",
    "FI": "Europe",
    "FR": "Europe",
    "DE": "Europe",
    "GI": "Europe",
    "GR": "Europe",
    "GG": "Europe",
    "VA": "Europe",
    "HU": "Europe",
    "IS": "Europe",
    "IE": "Europe",
    "IM": "Europe",
    "IT": "Europe",
    "JE": "Europe",
    "XK": "Europe",
    "LV": "Europe",
    "LI": "Europe",
    "LT": "Europe",
    "LU": "Europe",
    "MT": "Europe",
    "MD": "Europe",
    "MC": "Europe",
    "ME": "Europe",
    "NL": "Europe",
    "MK": "Europe",
    "NO": "Europe",
    "PL": "Europe",
    "PT": "Europe",
    "RO": "Europe",
    "RU": "Europe",
    "SM": "Europe",
    "RS": "Europe",
    "SK": "Europe",
    "SI": "Europe",
    "ES": "Europe",
    "SJ": "Europe",
    "SE": "Europe",
    "CH": "Europe",
    "UA": "Europe",
    "GB": "Europe",
    "AI": "North America",
    "AX": "Europe",
    "BV": "Antarctica",
    "GS": "Antarctica",
    "HM": "Antarctica",
    "AG": "North America",
    "AW": "North America",
    "BS": "North America",
    "BB": "North America",
    "BZ": "North America",
    "BM": "North America",
    "BQ": "North America",
    "VG": "North America",
    "KY": "North America",
    "CA": "North America",
    "CR": "North America",
    "CU": "North America",
    "CW": "North America",
    "DM": "North America",
    "DO": "North America",
    "SV": "North America",
    "GL": "North America",
    "GD": "North America",
    "GP": "North America",
    "GT": "North America",
    "HT": "North America",
    "HN": "North America",
    "JM": "North America",
    "MQ": "North America",
    "MX": "North America",
    "MS": "North America",
    "NI": "North America",
    "PA": "North America",
    "PR": "North America",
    "BL": "North America",
    "KN": "North America",
    "LC": "North America",
    "MF": "North America",
    "PM": "North America",
    "VC": "North America",
    "SX": "North America",
    "TT": "North America",
    "TC": "North America",
    "VI": "North America",
    "US": "North America",
    "AS": "Oceania",
    "AU": "Oceania",
    "CC": "Oceania",
    "CK": "Oceania",
    "CX": "Oceania",
    "FJ": "Oceania",
    "PF": "Oceania",
    "GU": "Oceania",
    "KI": "Oceania",
    "MH": "Oceania",
    "FM": "Oceania",
    "NR": "Oceania",
    "NC": "Oceania",
    "NZ": "Oceania",
    "NU": "Oceania",
    "NF": "Oceania",
    "MP": "Oceania",
    "PW": "Oceania",
    "PG": "Oceania",
    "PN": "Oceania",
    "WS": "Oceania",
    "SB": "Oceania",
    "TK": "Oceania",
    "TO": "Oceania",
    "TV": "Oceania",
    "VU": "Oceania",
    "WF": "Oceania",
    "AR": "South America",
    "BO": "South America",
    "FK": "South America",
    "BR": "South America",
    "CL": "South America",
    "CO": "South America",
    "EC": "South America",
    "GF": "South America",
    "GY": "South America",
    "PY": "South America",
    "PE": "South America",
    "SR": "South America",
    "UY": "South America",
    "VE": "South America",
}

# ---------------------------------------------------------------------------
# ISO 3166-1 alpha-2 -> ISO 639-1 language code
# ---------------------------------------------------------------------------
# Dominant language for each country.  For multilingual countries the most
# common business/official language is chosen (e.g. CH -> de, BE -> nl,
# IN -> en).  Only ISO 639-1 two-letter codes that exist in the standard
# are used — see https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes.

_COUNTRY_TO_LANGUAGE: dict[str, str] = {
    "AF": "ps",
    "AL": "sq",
    "DZ": "ar",
    "AD": "ca",
    "AO": "pt",
    "AG": "en",
    "AR": "es",
    "AM": "hy",
    "AU": "en",
    "AT": "de",
    "AZ": "az",
    "BS": "en",
    "BH": "ar",
    "BD": "bn",
    "BB": "en",
    "BY": "be",
    "BE": "nl",
    "BZ": "en",
    "BJ": "fr",
    "BT": "dz",
    "BO": "es",
    "BA": "bs",
    "BW": "en",
    "BR": "pt",
    "BN": "ms",
    "BG": "bg",
    "BF": "fr",
    "BI": "fr",
    "CV": "pt",
    "KH": "km",
    "CM": "fr",
    "CA": "en",
    "CF": "fr",
    "TD": "fr",
    "CL": "es",
    "CN": "zh",
    "CO": "es",
    "KM": "ar",
    "CG": "fr",
    "CD": "fr",
    "CR": "es",
    "HR": "hr",
    "CU": "es",
    "CY": "el",
    "CZ": "cs",
    "DK": "da",
    "DJ": "fr",
    "DM": "en",
    "DO": "es",
    "EC": "es",
    "EG": "ar",
    "SV": "es",
    "GQ": "es",
    "ER": "ti",
    "EE": "et",
    "SZ": "en",
    "ET": "am",
    "FJ": "en",
    "FI": "fi",
    "FR": "fr",
    "GA": "fr",
    "GM": "en",
    "GE": "ka",
    "DE": "de",
    "GH": "en",
    "GR": "el",
    "GD": "en",
    "GT": "es",
    "GN": "fr",
    "GW": "pt",
    "GY": "en",
    "HT": "fr",
    "HN": "es",
    "HK": "en",
    "HU": "hu",
    "IS": "is",
    "IN": "en",
    "ID": "id",
    "IR": "fa",
    "IQ": "ar",
    "IE": "en",
    "IL": "he",
    "IT": "it",
    "CI": "fr",
    "JM": "en",
    "JP": "ja",
    "JO": "ar",
    "KZ": "kk",
    "KE": "sw",
    "KI": "en",
    "KR": "ko",
    "KP": "ko",
    "XK": "sq",
    "KW": "ar",
    "KG": "ky",
    "LA": "lo",
    "LV": "lv",
    "LB": "ar",
    "LS": "en",
    "LR": "en",
    "LY": "ar",
    "LI": "de",
    "LT": "lt",
    "LU": "lb",
    "MO": "zh",
    "MG": "mg",
    "MW": "en",
    "MY": "ms",
    "MV": "dv",
    "ML": "fr",
    "MT": "mt",
    "MH": "en",
    "MR": "ar",
    "MU": "en",
    "MX": "es",
    "FM": "en",
    "MD": "ro",
    "MC": "fr",
    "MN": "mn",
    "ME": "sr",
    "MA": "ar",
    "MZ": "pt",
    "MM": "my",
    "NA": "en",
    "NR": "na",
    "NP": "ne",
    "NL": "nl",
    "NZ": "en",
    "NI": "es",
    "NE": "fr",
    "NG": "en",
    "MK": "mk",
    "NO": "nb",
    "OM": "ar",
    "PK": "ur",
    "PW": "en",
    "PS": "ar",
    "PA": "es",
    "PG": "en",
    "PY": "es",
    "PE": "es",
    "PH": "tl",
    "PL": "pl",
    "PT": "pt",
    "QA": "ar",
    "RO": "ro",
    "RU": "ru",
    "RW": "rw",
    "KN": "en",
    "LC": "en",
    "VC": "en",
    "WS": "sm",
    "SM": "it",
    "ST": "pt",
    "SA": "ar",
    "SN": "fr",
    "RS": "sr",
    "SC": "en",
    "SL": "en",
    "SG": "en",
    "SK": "sk",
    "SI": "sl",
    "SB": "en",
    "SO": "so",
    "ZA": "en",
    "SS": "en",
    "ES": "es",
    "LK": "si",
    "SD": "ar",
    "SR": "nl",
    "SE": "sv",
    "CH": "de",
    "SY": "ar",
    "TW": "zh",
    "TJ": "tg",
    "TZ": "sw",
    "TH": "th",
    "TL": "tet",
    "TG": "fr",
    "TO": "en",
    "TT": "en",
    "TN": "ar",
    "TR": "tr",
    "TM": "tk",
    "TV": "en",
    "UG": "en",
    "UA": "uk",
    "AE": "ar",
    "GB": "en",
    "US": "en",
    "UY": "es",
    "UZ": "uz",
    "VU": "bi",
    "VA": "it",
    "VE": "es",
    "VN": "vi",
    "YE": "ar",
    "YT": "fr",
    "ZM": "en",
    "ZW": "en",
    "AI": "en",
    "AQ": "en",
    "AS": "en",
    "AW": "nl",
    "AX": "sv",
    "BL": "fr",
    "BM": "en",
    "BQ": "nl",
    "BV": "nb",
    "CC": "ms",
    "CK": "en",
    "CW": "nl",
    "CX": "en",
    "EH": "ar",
    "FK": "en",
    "FO": "fo",
    "GF": "fr",
    "GG": "en",
    "GI": "en",
    "GL": "kl",
    "GP": "fr",
    "GS": "en",
    "GU": "en",
    "HM": "en",
    "IM": "en",
    "IO": "en",
    "JE": "en",
    "KY": "en",
    "MF": "fr",
    "MP": "en",
    "MQ": "fr",
    "MS": "en",
    "NC": "fr",
    "NF": "en",
    "NU": "en",
    "PF": "fr",
    "PM": "fr",
    "PN": "en",
    "PR": "es",
    "RE": "fr",
    "SH": "en",
    "SJ": "nb",
    "SX": "nl",
    "TC": "en",
    "TK": "en",
    "VG": "en",
    "VI": "en",
    "WF": "fr",
}

_TWO_LETTER_CODE_RE = _re.compile(r"^[A-Za-z]{2}$")


def country_to_region(country_iso: str | None) -> str | None:
    """Return the continent name for a given ISO 3166-1 alpha-2 country code.
    Returns ``None`` when ``country_iso`` is ``None`` or the code is not
    recognised.
    """
    if country_iso is None:
        return None
    return _COUNTRY_TO_REGION.get(country_iso.upper())


def infer_country_iso(location: str | None) -> str | None:
    """Try to extract an ISO 3166-1 alpha-2 country code from a free-text
    location string.

    Strategy (in order):
    1. If the location already looks like an ISO code (2 letters), validate
       it against the continent table.
    2. Look for a known country name, US state, or Canadian province in the
       location text.

    Returns ``None`` when nothing can be inferred.
    """
    if not isinstance(location, str) or not location.strip():
        return None

    text = location.strip()

    if _TWO_LETTER_CODE_RE.match(text):
        upper = text.upper()
        if upper in _COUNTRY_TO_REGION:
            return upper

    words = (
        text.lower()
        .replace(",", " ")
        .replace("-", " ")
        .replace("\u2014", " ")
        .replace("\u2013", " ")
        .split()
    )

    for word in words:
        if len(word) == 2 and word.upper() in _COUNTRY_TO_REGION:
            return word.upper()

    for n in range(min(5, len(words)), 0, -1):
        for i in range(len(words) - n + 1):
            phrase = " ".join(words[i : i + n])
            result = _LOCATION_ISO_LOOKUP.get(phrase)
            if result is not None:
                return result

    return None


def infer_language(country_iso: str | None) -> str | None:
    """Return the dominant language ISO 639-1 code for a country.

    Uses a static mapping of ISO 3166-1 alpha-2 → ISO 639-1. For
    multilingual countries the most common business language is chosen
    (e.g. ``"CH"`` → ``"de"``, ``"BE"`` → ``"nl"``, ``"IN"`` → ``"en"``).

    Returns ``None`` when ``country_iso`` is ``None`` or the code is not
    recognised.
    """
    if country_iso is None:
        return None
    return _COUNTRY_TO_LANGUAGE.get(country_iso.upper())
